<?xml version="1.0" encoding="UTF-8"?>
<definitions name="asyncIsProductAvailable" targetNamespace="http://j2ee.netbeans.org/wsdl/ElectricAppliancesModule/asyncIsProductAvailable"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://j2ee.netbeans.org/wsdl/ElectricAppliancesModule/asyncIsProductAvailable" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns6="http://xml.netbeans.org/schema/Service4" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <types>
        <xsd:schema targetNamespace="http://j2ee.netbeans.org/wsdl/ElectricAppliancesModule/asyncIsProductAvailable">
            <xsd:import schemaLocation="../../../../localhost_8080/ElectricAppliancesWebService/Service4.xsd" namespace="http://xml.netbeans.org/schema/Service4"/>
        </xsd:schema>
    </types>
    <message name="isProductAvailableOperationRequest">
        <part name="productId" type="xsd:string"/>
    </message>
    <message name="isProductAvailableOperationResponse">
        <part name="booleanValue" type="xsd:boolean"/>
    </message>
    <portType name="isProductAvailablePortType">
        <operation name="isProductAvailableOperation">
            <input name="input1" message="tns:isProductAvailableOperationRequest"/>
            <output name="output1" message="tns:isProductAvailableOperationResponse"/>
        </operation>
    </portType>
    <binding name="isProductAvailableBinding" type="tns:isProductAvailablePortType">
        <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="isProductAvailableOperation">
            <soap:operation/>
            <input name="input1">
                <soap:body use="literal" namespace="http://j2ee.netbeans.org/wsdl/ElectricAppliancesModule/asyncIsProductAvailable"/>
            </input>
            <output name="output1">
                <soap:body use="literal" namespace="http://j2ee.netbeans.org/wsdl/ElectricAppliancesModule/asyncIsProductAvailable"/>
            </output>
        </operation>
    </binding>
    <service name="isProductAvailableService">
        <port name="isProductAvailablePort" binding="tns:isProductAvailableBinding">
            <soap:address location="http://localhost:${HttpDefaultPort}/isProductAvailableService/isProductAvailablePort"/>
        </port>
    </service>
    <plnk:partnerLinkType name="isProductAvailable">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes.
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="isProductAvailablePortTypeRole" portType="tns:isProductAvailablePortType"/>
    </plnk:partnerLinkType>
</definitions>
