<?xml version="1.0" encoding="UTF-8"?>
<definitions name="asyncFindCart" targetNamespace="http://j2ee.netbeans.org/wsdl/ElectricAppliancesModule/asyncFindCart"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://j2ee.netbeans.org/wsdl/ElectricAppliancesModule/asyncFindCart" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns2="http://xml.netbeans.org/schema/Service2" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <types>
        <xsd:schema targetNamespace="http://j2ee.netbeans.org/wsdl/ElectricAppliancesModule/asyncFindCart">
            <xsd:import schemaLocation="../../../../localhost_8080/ElectricAppliancesWebService/Service2.xsd" namespace="http://xml.netbeans.org/schema/Service2"/>
        </xsd:schema>
    </types>
    <message name="findCartOperationRequest">
        <part name="orderId" type="xsd:string"/>
    </message>
    <message name="findCartOperationResponse">
        <part name="cart" type="ns2:cart"/>
    </message>
    <portType name="findCartPortType">
        <operation name="findCartOperation">
            <input name="input1" message="tns:findCartOperationRequest"/>
            <output name="output1" message="tns:findCartOperationResponse"/>
        </operation>
    </portType>
    <binding name="findCartBinding" type="tns:findCartPortType">
        <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="findCartOperation">
            <soap:operation/>
            <input name="input1">
                <soap:body use="literal" namespace="http://j2ee.netbeans.org/wsdl/ElectricAppliancesModule/asyncFindCart"/>
            </input>
            <output name="output1">
                <soap:body use="literal" namespace="http://j2ee.netbeans.org/wsdl/ElectricAppliancesModule/asyncFindCart"/>
            </output>
        </operation>
    </binding>
    <service name="findCartService">
        <port name="findCartPort" binding="tns:findCartBinding">
            <soap:address location="http://localhost:${HttpDefaultPort}/findCartService/findCartPort"/>
        </port>
    </service>
    <plnk:partnerLinkType name="findCart">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes.
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="findCartPortTypeRole" portType="tns:findCartPortType"/>
    </plnk:partnerLinkType>
</definitions>
