<?xml version="1.0" encoding="UTF-8"?>
<definitions name="businessPrecess2" targetNamespace="http://j2ee.netbeans.org/wsdl/ElectricAppliancesModule/businessPrecess2"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://j2ee.netbeans.org/wsdl/ElectricAppliancesModule/businessPrecess2" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <types/>
    <message name="executeRequest">
        <part name="orderId" type="xsd:string"/>
    </message>
    <message name="executeResponse">
        <part name="part1" type="xsd:string"/>
    </message>
    <portType name="businessPrecess2PortType">
        <operation name="execute">
            <input name="input1" message="tns:executeRequest"/>
            <output name="output1" message="tns:executeResponse"/>
        </operation>
    </portType>
    <binding name="businessPrecess2Binding" type="tns:businessPrecess2PortType">
        <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="execute">
            <soap:operation/>
            <input name="input1">
                <soap:body use="literal" namespace="http://j2ee.netbeans.org/wsdl/ElectricAppliancesModule/businessPrecess2"/>
            </input>
            <output name="output1">
                <soap:body use="literal" namespace="http://j2ee.netbeans.org/wsdl/ElectricAppliancesModule/businessPrecess2"/>
            </output>
        </operation>
    </binding>
    <service name="businessPrecess2Service">
        <port name="businessPrecess2Port" binding="tns:businessPrecess2Binding">
            <soap:address location="http://localhost:${HttpDefaultPort}/ode/processes/businessPrecess2Service/businessPrecess2Port"/>
        </port>
    </service>
    <plnk:partnerLinkType name="businessPrecess2">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes.
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="businessPrecess2PortTypeRole" portType="tns:businessPrecess2PortType"/>
    </plnk:partnerLinkType>
</definitions>


